#! /bin/bash
#------------------------------------------------------------------------------
# License
#     This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#     For more information about these patches, visit:
#         http://www.bluecape.com.pt/blueCFD
#
#     OpenFOAM's official site: http://www.openfoam.com
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     genOPENMPIstubs
#
# Description
#     This script generates the link library and prepares the include 
#   files for the pre-built version of Open-MPI for Windows.
#
#------------------------------------------------------------------------------

if ! isMinGW; then
  echo "Error: this script is meant to be used for MinGW compilers only!"
  exit 1
fi

# run from third-party directory only
cd ${0%/*} || exit 1
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
. etc/tools/makeExtraThirdPartyFunctions

#end of initializations -------------------------------------------

create_gcccompatible_library()
{
  echo -e "\033[1m creating libmpi.a \033[0m"
  WM_DLLTOOL=`echo $WM_CC | sed s/gcc/dlltool/`
  cd $MPI_ARCH_PATH/lib
  pexports -o $MPI_ARCH_PATH/bin/libmpi.dll > openmpi.def
  $WM_DLLTOOL -d openmpi.def -l libmpi.a -D libmpi.dll
}

patch_mpi_includes()
{
  echo -e "\033[1m patching mpi.h \033[0m"
  if [ "$WM_ARCH_OPTION" = "64" ]; then
    cd $MPI_ARCH_PATH/include
echo '--- mpi_orig.h  2011-11-02 16:41:18.335207542 +0000
+++ mpi.h 2011-11-02 16:41:40.202866671 +0000
@@ -178,7 +178,7 @@
 #define OMPI_PROVIDE_MPI_FILE_INTERFACE 1
 
 #ifndef OMPI_DECLSPEC
-#  if defined(WIN32) || defined(_WIN32)
+#  if defined(WIN32) || defined(_WIN32) || defined(WIN64) || defined(_WIN64)
 #    if defined(OMPI_IMPORTS)
 #      define OMPI_DECLSPEC        __declspec(dllimport)
 #    else
' | patch -p0

  fi
}


#script start ------------------------------------------------------

if [ ! -e "$MPI_ARCH_PATH/bin/libmpi.dll" ]; then
  ./get-em so openmpi-win=default || {
    echo "Unable to retrieve and unpack necessary files for Open-MPI."
    exit 1
  }
fi

if [ ! -e "$MPI_ARCH_PATH/lib/libmpi.a" ]; then

  #this function will take care of the logistics associated with using pexports.
  build_pexports

  echo -e "\033[1m Generating Open-MPI library interfaces for MinGW... \033[0m"

  create_gcccompatible_library
  patch_mpi_includes
  echo -e "\033[1m All done. \033[0m"
else
  echo -e "\033[1m Open-MPI library interfaces for MinGW are already built and ready to use. \033[0m"
fi
