#!/bin/sh
#------------------------------------------------------------------------------
# License
#
#     This file is based on the branch "get-em" available here:
#         https://github.com/wyldckat/ThirdParty-2.0.x/commits/get-em
#
#     These modifications have not been endorsed by OpenCFD Ltd, SGI corp nor
#   the OpenFOAM Foundation.
#
#     It's licensed under the same license of the target software, namely GPL
#   v3 or above (see <http://www.gnu.org/licenses/>).
#
#     The target software is OpenFOAM(R) <http://www.openfoam.com>, which is
#   trademarked by and Copyright (C) OpenFOAM Foundation.
#
# File
#     etc/tools/get-em/mingwrt
#
# Description
#     This script will gather the necessary information about the application.
#     This script expects to be executed in the base folder where the get-em script is.
#
#------------------------------------------------------------------------------

versionVar="mingw32rt_version"
appName="mingwrt"
appDefaultSep="-"
appFileExt="tar.gz"


#
# Shows the description for this application.
#
GE_showDesc()
{
  echo "mingwrt - Retrieve the MinGW-RT package. Size: 500kB to 1MB"
}


#
# Updates the file defined in $versionCacheFile, using the mirror url $1 and
# uses the $testFile as a sandbox.
#
GE_update()
{
  wget "$1" -O $testFile > /dev/null 2>&1
  grep -e '/'$appName'-[0-9]\.[0-9\.]*/' $testFile | \
    sed -e 's=.*/\('$appName'-[0-9]\.[0-9\.]*\)/.*=\1=' -e 's_-_=_' | \
    sort -u > $versionCacheFile
  rm $testFile
}


#
# Receives the mirror url $1, the real version $2 and the variable $appFileExt.
# Shows the full url for the file to be downloaded.
#
GE_geturl()
{
  echo ${1}$appName-${2}/$appName-$2-mingw32-dev.$appFileExt
}


#
# Echoes the relative path of the target folder. Receives the real version $1.
#
GE_getfolder()
{
  echo $appName-$1
}


#
# Echoes the number of folder levels counting from the left that the unpacker
# should drop. This is (or at least it should be) a prevention mechanism for
# tar/zipbombs.
#
GE_levels()
{
  echo 0
}


# Finally source the master script
. etc/tools/get-emScriptFunctions
